spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@ds125914.mlab.com:25914/aerine
  jackson:
    serialization:
      fail-on-empty-beans: false


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    com.arturo.aerineapi: DEBUG

security:
  oauth2:
    resource:
      filterOrder: 3
  signingKey: HolaHola
  encodingStrength: 256
  securityRealm: HolaRealm
  jwt:
    clientId: clientId
    clientSecret: "clientSecret"
    grantType: password
    scopeRead: read
    scopeWrite: write
    resourceIds: oauth2-server
  cors:
    origin: "http://localhost:8100"
    header: "Authorization"
    method: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    credential: true

server:
  contextPath: /aerine-api
  port: 8080

game:
  servers:
    - "Server 1"
    - "Server 2"